var VALIDATORS = [];
var MODELS = [];
var SPECIALTY_FORMS = [];
var SPECIALTY_INTAKE_FORMS = [];
var SPECIALTY;
var AC_SPECIALTY = 'ac';
var AM_SPECIALTY = 'am';
var PASSWORD_RESET="Reset";
var BH_SPECIALTY = 'bh';
var DOM_SPECIALTY = 'dom';
var PMD_SPECIALTY = 'pmd';
var POT_SPECIALTY = 'pot';
var GP_SPECIALTY = 'gp';
var PRACTICE;
var AAC_EVAL_TYPE =  'aac';
var ACTIVE = "active";
var CANCEL = "cancel";
var CANCELLED_LETTER_MODE = "cancelled_letter_mode";
var CLIENT_STATUS_AUTHORIZED = 1;
var CLIENT_STATUS_NOT_FOUND = 0;
var CLIENT_STATUS_INVALID_PASSWORD = -1;
var CLIENT_STATUS_INACTIVE = -2;
var CLIENT_STATUS_PASSWORD_ALREADY_CREATED = -3;
var CLIENT_STATUS_RECOVERY_CODE_EXPIRED = -4;
var CLIENT_STATUS_RECOVERY_CODE_ALREADY_USED = -5;
var CLIENT_STATUS_ACTIVATION_CODE_EXPIRED = -6;
var CLIENT_STATUS_ACTIVATION_CODE_ALREADY_USED = -7;
var PENDING_TRANSACTION="pending_transaction";

var NOTIFICATION_TEXT;

var CLINICAL = "clinical";
var CONS = "cons";
var CREATE = "create";
var CLOSED = true;
var DECREASE = "decrease";
var DEFAULT_APP_PATH = "/cfpm/";
var DELETE = "delete";
var DELETED = "deleted";
var DRAFT = true;
var DO_AUTO_LOGOUT = true;
var DO_AUTO_SERVER_LOGOUT = true;
var DO_RELOAD = true;
var DO_SCROLL = true;
var DONT_SCROLL = false;
var EDIT = "edit";
var EVAL = "eval";
var FORM_CLOSE = "close";
var FORM_DELETE = "delete";
var FORM_OPEN = "open";
var INCREASE = "increase";
var INTEGER_TYPE = "integer";
var IS_PATIENT = true;
var LETTER_READ = 'read';
var LETTER_SAVED = 'saved';
var MESSAGE_DELETED = 'deleted';
var MESSAGE_INBOX = 'inbox';
var MESSAGE_DRAFT = 'draft';
var MESSAGE_SAVED = 'saved';
var MESSAGE_SENT = 'sent';
var MESSAGE_COMPOSE = 'message-compose-btn';
var MESSAGE_TYPE_GENERAL = 1;
var MESSAGE_TYPE_MEDICAL_ADVICE = 2;
var MESSAGE_TYPE_RX_RENEWAL = 3;
var MESSAGE_TYPE_APPT_REQUEST = 4;
var MESSAGE_TYPE_INITIAL_APPT_REQUEST = 5;
var NEW = "new";
var NEW_LETTER_MODE = "new_letter_mode";
var NO_PRINT = false;
var NOT_A_RELOAD = false;
var NOT_CLOSED = false;
var NOT_DRAFT = false;
var NOT_PATIENT = false;
var NOT_READING_MESSAGE = false;
var OFFICE = "office";
var ONE_MINUTE = 60000;
var ONE_SECOND =  1000;
var OT_EVAL_TYPE =  'ot';
var PAID = "paid";
var PATIENT_CLIENT_TYPE = "patient";
var PM_MODULE = "pm";
var PRINT = true;
var PORTAL_MODULE = "portal";
var PASSWORD_PLACEHOLDER = 'not a password';
var PROFILE_PLACEHOLDER_SM="assets/images/headshot_placeholder_sm.jpg";
var READING_MESSAGE = true;
var RESOLVED = "resolved";
var RETURN_CODE_DUP_EMAIL = -1;
var RETURN_CODE_INVALID_PASSWORD = -3;
var RETURN_CODE_INVALID_SSN = -3;
var RETURN_CODE_DUP_USERNAME = -1;
var RETURN_CODE_DUP_USER_EMAIL = -3;
var RETURN_CODE_VALID = 1;
var SAVED = 'saved';
var SENT = "sent";
var SENT_LETTER_MODE = "sent_letter_mode";
var SPEECH_EVAL_TYPE =  'speech';
var SITE_MODULE = "site";
var STORE_MODULE = "store";
var TEXT_TYPE= "text";
var TX = "tx";
var UPDATE = "update";
var USER_ACTIVE = 1;
var USER_CLIENT_TYPE = "user";
var VIEW = "view";
var VIEW_LETTER_MODE = "view_letter_mode";
    

var app_aacEval;
var app_aacIntake;
var app_intakeFormValidators;
var app_activityLogClinicianSearchTypeAheads;
var app_activityLogPatientSearchTypeAheads;
var app_activityLogs;
var app_adminScreenCache;
var app_adminScreenItemCache;
var app_appointmentsCache;
var app_apptTypes;
var app_billingTicket= null;
var app_billingTicketEntry;
var app_billingTicketEntryId;
var app_calendar = null;
var app_calendarView = 'month';
var app_card = null;
var app_client = null;
var app_clientFullName;
var app_clientProperties;
var app_clientType;
var app_clinicianActivityTypeAheads;
var app_clinicianInfo;
var app_clinicianLocations;
var app_clinicianPatients;
var app_clinicianPatientsSelectOptions;
var app_clinicians;
var app_credentials;
var app_dashboardCache;
var app_date;
var app_evalMode = null;
var app_fbabipId;
var app_finalScreenButton;
var app_finalScreenNumber;
var app_form = null;
var app_formClassName;
var app_formId;
var app_formNewInstanceId;
var app_forms = {};
var app_gender;
var app_goalBankItem;
var app_goalBankItemId;
var app_goalBankItems;
var app_groupByPatientsLog;
var app_guardian = null;
var app_guardianLastNameTypeAheads;
var app_guardians;
var app_headerFooterCache;
var app_hideElementListCache;
var app_idleInterval;
var app_idleTime = 0;
var app_formError;
var app_intakeFormIndices = [];
var app_invoice;
var app_invoiceId;
var app_leadMgmtCache;
var app_letter = null;
var app_letterId;
var app_lettersCache;
var app_locations;
var app_ltg
var app_message;
var app_messageMailbox;
var app_messages;
var app_messageBCCRecipientsInput;
var app_messagesCache;
var app_messageCCRecipientsInput;
var app_messagePrimaryRecipientsInput;
var app_messageValidRecipientsInput;
var app_module;
var app_missingFields = []; 
var app_notificationText;
var app_openFormId = null;
var app_otEvals = null;
var app_otIntakes = null;
var app_otProgs = null; 
var app_otTxs = null; 
var app_parkWarningDisplayed;
var app_patient = null;
var app_patientForm = null;
var app_patientFormId;
var app_patientFullName;
var app_patientId;
var app_patientProfileImage;
var app_patientChartCache;
var app_patientChartItemCache;
var app_patientClinicians;
var app_patientForms;
var app_patientInfo;
var app_patientIntake;
var app_patientIntakeId;
var app_patientInvoices;
var app_patientLetters;
var app_patients;
var app_patientSearchTypeAheads;
var app_potPatientForms;
var app_practiceClientProperties;
var app_practiceForms;
var app_previousScreen;
var app_profileImageTempPath = "";
var app_programs;
var app_reportList;
var app_reportName;
var app_reportsCache;
var app_reportTitle;
var app_roles;
var app_rxRenewalCache;
var app_scheduleCache;
var app_screen;
var app_selectedClinician;
var app_sendMessageCache;
var app_settingsCache;
var app_signinCache;
var app_specialtyClientProperties;
var app_speechEval;
var app_speechIntake;
var app_stgDescriptions = null;
var app_templateFormPrefix;
var app_templateFormName;
var app_templateFormTitle;
var app_templateScreenName;
var app_templateClassName;
var app_txNote;
var app_txNotes;
var app_validMessageRecipients;
var app_userDashboard;
var app_userLocations;
var app_users;
var app_guardian;
var app_usStates;
var app_cptModifiers; 
var app_waitListPatients;
var app_yourRecordsCache;
var app_pm_nestedFormOffsetClass;
var app_patientEncounter;
