//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 12:19:07 PM EDT 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryOutcome-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QueryOutcome-list">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ok"/>
 *     &lt;enumeration value="limited"/>
 *     &lt;enumeration value="refused"/>
 *     &lt;enumeration value="error"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QueryOutcome-list")
@XmlEnum
public enum QueryOutcomeList {


    /**
     * The query was processed successfully.
     * 
     */
    @XmlEnumValue("ok")
    OK("ok"),

    /**
     * The query was processed successfully, but some additional limitations were added.
     * 
     */
    @XmlEnumValue("limited")
    LIMITED("limited"),

    /**
     * The server refused to process the query.
     * 
     */
    @XmlEnumValue("refused")
    REFUSED("refused"),

    /**
     * The server tried to process the query, but some error occurred.
     * 
     */
    @XmlEnumValue("error")
    ERROR("error");
    private final java.lang.String value;

    QueryOutcomeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static QueryOutcomeList fromValue(java.lang.String v) {
        for (QueryOutcomeList c: QueryOutcomeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
