//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 12:19:07 PM EDT 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RestfulConformanceMode-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RestfulConformanceMode-list">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="client"/>
 *     &lt;enumeration value="server"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RestfulConformanceMode-list")
@XmlEnum
public enum RestfulConformanceModeList {


    /**
     * The application acts as a server for this resource.
     * 
     */
    @XmlEnumValue("client")
    CLIENT("client"),

    /**
     * The application acts as a client for this resource.
     * 
     */
    @XmlEnumValue("server")
    SERVER("server");
    private final java.lang.String value;

    RestfulConformanceModeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static RestfulConformanceModeList fromValue(java.lang.String v) {
        for (RestfulConformanceModeList c: RestfulConformanceModeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
